# Generated by Django 4.0.2 on 2022-02-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Team',
        ),
    ]
