# Generated by Django 4.0.2 on 2022-02-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_rename_genre_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='number_in_stock',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='genre',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='release_year',
        ),
    ]
