# Generated by Django 4.0.2 on 2022-02-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_rename_date_created_tool_date_rename_title_tool_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='date',
            new_name='date_created',
        ),
    ]
